% A script that runs a phreeqc string
% It is kind of messy because of matlab's way of treating strings
iph = IPhreeqc(); % load the library
iph = iph.CreateIPhreeqc(); % create an IPhreeqc instance
iph_string = ['SOLUTION 1 brine \n' ...
    'pH      7.0 \n' ...
    'temp    25.0 \n' ...
    'CaCl2    1.0 \n' ...
    'END \n' ...
    'SELECTED_OUTPUT 1 \n'...
    '-reset false \n'...
    '-totals Na Cl \n'...
    'END'];
out_string = iph.RunPhreeqcString(iph_string, database_file('phreeqc.dat'));
disp(out_string)
% the above function does the following:
% iph.SetOutputStringOn(true);
% iph.LoadDatabase(database_file('phreeqc.dat'));
% iph.RunFile('IPhreeqc_test2.pqc');
% out_string = iph.GetOutputString();
% disp(out_string); % display the phreeqc output string
iph.DestroyIPhreeqc();